name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if your branch is named master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'  # This is where your index.html is (root directory)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
